import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowRight,BookOpen,Camera,Check,CheckCircle2,ChevronRight,Clock,FileText,FileVideo2,FolderOpen,History,LayoutDashboard,Link2,LoaderCircle,Monitor,Play,RefreshCw,Square,Trash2,UploadCloud,Video,X,AlertCircle,ScanLine} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,BarChart,Bar,Legend} from 'recharts';
import GaitProfile, {type Profile} from './GaitProfile';
import './styles.css';
import './profile.css';
import './desktop.css';

type Scenario='W'|'OW'|'WT';
type Route={type:string;name:string;weight_sha256:string;input:string;selection:string;weight:string;frame_count_contract?:string};
type Health={service:string;routes:Record<Scenario,Route>;video:{ready:boolean;preview_ready?:boolean;research_preview_ready?:boolean;demo_w_grading?:boolean;reason:string;missing:string[]};busy:boolean};
type Sample={id:string;name:string;scenario:Scenario;reference_label:string;coordinate_source:string;stride_count:number;description:string};
type Result={subject_selection?:{selected_tracks?:number[];segment_note?:string|null};profile?:Profile;research_version?:string;research_error?:string;classification_status?:'experimental';preprocessing_note?:string;exporter_version?:string;kind?:string;limitation?:string;still_url?:string|null;frames?:number;valid_frames?:number;pose_model?:string;pose_weight_sha256?:string;grade:number;probabilities:number[];classes:string[];scenario:Scenario;stride_count:number;valid_ratio:number|null;coordinate_source:string;provenance:string;overlay_url:string|null;video_url:string|null;model:Route;aggregation:string;sample:boolean;curves:Record<string,number|null>[];rom:{joint:string;left:number|null;right:number|null}[];skeleton:number[][][];edges:number[][];display_source:string;phase_note:string;radar_note:string;probability_note:string;quality_note:string};
type Task={id:string;name:string;scenario:Scenario;mode:string;status:string;stage:string;error:string|null;created:string;elapsed:number;result:Result|null};
const scenarios:Record<Scenario,{name:string;hint:string}>={W:{name:'普通行走',hint:'原始 stride ExtraTrees'},OW:{name:'跨障碍行走',hint:'work123 integrate CNN'},WT:{name:'边走边说',hint:'work123 integrate CNN'}};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,init);if(!r.ok){const body=await r.json().catch(()=>({detail:'服务连接失败'}));throw new Error(typeof body.detail==='string'?body.detail:'请求失败，请检查输入或稍后重试')}return r.json()}

function Skeleton({result}:{result:Result}){
 const canvas=useRef<HTMLCanvasElement>(null);const [phase,setPhase]=useState(0);const [playing,setPlaying]=useState(true);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setPhase(v=>(v+1)%40),90);return()=>clearInterval(timer)},[playing]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const all=result.skeleton.flat();const minX=Math.min(...all.map(p=>p[0])),maxX=Math.max(...all.map(p=>p[0]));const heightAxis=result.research_version?2:1;const minY=Math.min(...all.map(p=>p[heightAxis])),maxY=Math.max(...all.map(p=>p[heightAxis]));const scale=Math.min(430/(maxX-minX||1),270/(maxY-minY||1));const project=(p:number[])=>[300+(p[0]-(maxX+minX)/2)*scale,175-(p[heightAxis]-(maxY+minY)/2)*scale];ctx.clearRect(0,0,600,350);ctx.strokeStyle='#dde8eb';ctx.lineWidth=1;for(let x=0;x<600;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,350);ctx.stroke()}for(let y=0;y<350;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(600,y);ctx.stroke()}const points=result.skeleton[phase];for(const [a,b] of result.edges){const p=project(points[a]),q=project(points[b]);ctx.strokeStyle=a>=12?'#5797c9':'#168b87';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.stroke()}for(const point of points){const p=project(point);ctx.fillStyle='#fff';ctx.strokeStyle='#183449';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p[0],p[1],4,0,Math.PI*2);ctx.fill();ctx.stroke()}},[phase,result]);
 return <div className="skeleton"><canvas ref={canvas} width={600} height={350} aria-label={result.research_version?'三维估计的 XZ 骨架投影':'真实三维步态数据的 XY 骨架投影'}/><div className="skeleton-controls"><button className="icon-button" onClick={()=>setPlaying(v=>!v)} aria-label={playing?'暂停骨架':'播放骨架'}>{playing?<Square size={15}/>:<Play size={15}/>}</button><input aria-label="步态相位" type="range" min={0} max={39} value={phase} onChange={e=>{setPlaying(false);setPhase(Number(e.target.value))}}/><span>{Math.round(phase*100/39)}%</span></div><small>{result.research_version?'三维周期 · XZ 投影':'三维周期 · XY 投影'}</small></div>
}

function ResearchPose({result:r}:{result:Result}){
 if(!r.research_version||!r.skeleton?.length)return null;
 return <><div className="section-heading"><h3>三维运动预览</h3></div><div className={r.classification_status==="experimental"?"research-single":"result-grid"}><div className="result-media"><Skeleton result={r}/></div>{r.classification_status!=="experimental"&&<div className="curve"><h3>代表周期 · 膝关节角度</h3><ResponsiveContainer width="100%" height={250}><LineChart data={r.curves} margin={{top:20,right:16,left:0,bottom:15}}><CartesianGrid stroke="#e8eef0" vertical={false}/><XAxis dataKey="phase" tickFormatter={v=>`${v}%`} minTickGap={40}/><YAxis domain={[0,180]} unit="°" width={42}/><Tooltip formatter={v=>Number(v).toFixed(1)+'°'}/><Legend/><Line dataKey="L膝" name="左膝" stroke="#168b87" dot={false} isAnimationActive={false}/><Line dataKey="R膝" name="右膝" stroke="#5797c9" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer><p className="caption">{r.phase_note}</p></div>}</div><div className="report-notes research-notes"><details><summary>三维数据说明</summary><p>{r.display_source}</p><p>处理版本：{r.research_version}。周期来自双脚相对运动，不代表已确认的足跟触地事件。</p></details></div></>;
}

function ResultView({task}:{task:Task}){
 const [joint,setJoint]=useState('膝');const r=task.result!;
 if(r.kind==='pose_preview')return <section className="result-panel printable" id="report"><div className="section-heading"><div><h2><Activity size={22}/>视频姿态预览</h2><p>{task.name} · {new Date(task.created).toLocaleString('zh-CN')}</p></div><button className="secondary no-print" onClick={()=>window.print()}><FileText size={17}/>导出采集报告</button></div><div className="result-origin"><CheckCircle2 size={17}/>{r.provenance}</div><div className="result-grid"><div className="result-media"><video controls src={r.overlay_url!}/>{r.still_url&&<img className="print-still" src={r.still_url} alt="视频骨架叠加静帧"/>}<p className="caption">二维骨架视频</p></div><div className="result-summary"><h3>采集质量</h3><dl><div><dt>已处理帧数</dt><dd>{r.frames} 帧</dd></div><div><dt>有效帧数</dt><dd>{r.valid_frames} 帧</dd></div><div><dt>有效帧占比</dt><dd>{((r.valid_ratio||0)*100).toFixed(1)}%</dd></div><div><dt>处理耗时</dt><dd>{task.elapsed.toFixed(2)} 秒</dd></div></dl><div className="pipeline-note"><AlertCircle size={18}/><span>{r.research_version?'已完成周期与三维运动科研预览；视频分级兼容性仍未通过验证，本次不输出等级。':r.limitation}</span></div></div></div><ResearchPose result={r}/><div className="report-notes"><details><summary>模型与数据说明</summary>{r.research_error&&<p>三维科研预览未完成：{r.research_error}</p>}<p>{r.pose_model}</p><p>姿态模型 SHA256：{r.pose_weight_sha256}</p><p>{r.quality_note}</p><p>本次未运行 W / OW / WT 分级模型，没有步态等级或类别概率。</p></details></div></section>;

 return <section className="result-panel printable" id="report"><div className="section-heading"><div><h2><Activity size={22}/>评估结果</h2><p>{task.name} · {scenarios[r.scenario].name} · {new Date(task.created).toLocaleString('zh-CN')}</p></div><button className="secondary no-print" onClick={()=>window.print()}><FileText size={17}/>导出报告</button></div>
 <div className="result-origin"><CheckCircle2 size={17}/>{r.classification_status==='experimental'?'现场视频 · W 模型':r.provenance}</div>
 {r.exporter_version==='reconstructed-exporter-v1'&&<p className="pipeline-note"><AlertCircle size={18}/>旧版视频实验结果：后续配对验证未通过，该等级不可作为已验证结果。</p>}
 {r.classification_status==='experimental'&&<p className="pipeline-note"><AlertCircle size={18}/><span>实验性结果 · 未验证，不用于诊断</span></p>}
 {r.subject_selection?.selected_tracks&&r.subject_selection.selected_tracks.length>1&&<p className="segment-note"><ScanLine size={17}/>已连接两段行走画面，请核对是否为同一人。</p>}
 <div className="result-grid"><div className="result-media">{r.overlay_url||r.video_url?<><video controls src={r.overlay_url||r.video_url!}/>{r.still_url&&<img className="print-still" src={r.still_url} alt="视频骨架叠加静帧"/>}</>:<Skeleton result={r}/>}<p className="caption">{r.overlay_url?'二维骨架叠加视频':r.video_url?'原始视频':'已有三维数据 · 非现场视频'}</p></div><div className="result-summary"><div className="grade-heading"><span>{r.classification_status==='experimental'?'实验性模型分级':'步态功能分级'}</span><strong>L{r.grade}<small>级</small></strong></div><div className="probability-list">{r.classes.map((label,i)=><div key={label}><div><span>{label}</span><b>{(r.probabilities[i]*100).toFixed(1)}%</b></div><div className="prob-track"><span style={{width:`${r.probabilities[i]*100}%`,background:i===r.grade?'#168b87':'#bdcdd6'}}/></div></div>)}</div><p className="caption">{r.classification_status==='experimental'?'模型概率未经校准':r.probability_note}</p><dl><div><dt>{r.classification_status==='experimental'?'候选运动周期':'完整步态周期'}</dt><dd>{r.stride_count} 个</dd></div><div><dt>有效帧占比</dt><dd>{r.valid_ratio===null?'未记录':`${(r.valid_ratio*100).toFixed(1)}%`}</dd></div><div><dt>分析耗时</dt><dd>{task.elapsed.toFixed(2)} 秒</dd></div></dl></div></div>
 {r.profile&&<GaitProfile profile={r.profile}/>}
 {r.classification_status==='experimental'&&<ResearchPose result={r}/>}
 <div className="charts"><div className="curve"><div className="chart-heading"><h3>关节角度曲线</h3><div className="mini-tabs no-print">{['髋','膝','踝'].map(j=><button className={j===joint?'selected':''} key={j} onClick={()=>setJoint(j)}>{j}关节</button>)}</div></div><ResponsiveContainer width="100%" height={230}><LineChart data={r.curves} margin={{top:15,right:18,left:0,bottom:14}}><CartesianGrid stroke="#e8eef0" vertical={false}/><XAxis dataKey="phase" tick={{fontSize:11}} tickFormatter={v=>`${v}%`} minTickGap={45}/><YAxis domain={[0,180]} tick={{fontSize:11}} unit="°" width={42}/><Tooltip labelFormatter={v=>`相位 ${v}%`} formatter={(v)=>[Number(v).toFixed(1)+'°']}/><Legend/><Line dataKey={'L'+joint} name={'左'+joint} stroke="#168b87" strokeWidth={2.3} dot={false} isAnimationActive={false}/><Line dataKey={'R'+joint} name={'右'+joint} stroke="#5797c9" strokeWidth={2.3} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="rom"><h3>左右关节活动范围</h3><ResponsiveContainer width="100%" height={245}><BarChart data={r.rom} margin={{top:20,right:12,left:0,bottom:12}}><CartesianGrid stroke="#e8eef0" vertical={false}/><XAxis dataKey="joint"/><YAxis width={40} unit="°" tick={{fontSize:11}}/><Tooltip formatter={v=>Number(v).toFixed(1)+'°'}/><Legend/><Bar dataKey="left" name="左侧" fill="#168b87" radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="right" name="右侧" fill="#5797c9" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></div>
 <div className="report-notes"><details><summary>模型与结果来源</summary>{r.preprocessing_note&&<p><b>预处理版本：</b>{r.preprocessing_note}</p>}<p>{r.display_source}</p><p>未标定的步长不显示为厘米。</p><p>{r.model.name} · {r.model.input}</p><p>权重 SHA256：{r.model.weight_sha256}</p><p>{r.model.selection}</p><p>{r.aggregation} · 坐标来源：{r.coordinate_source}</p><p>{r.quality_note}</p><p>{r.phase_note}</p></details>{r.classification_status!=='experimental'&&<p>科研演示结果，不作疾病诊断。</p>}</div></section>
}

function App(){
 const [page,setPage]=useState<'workbench'|'history'|'samples'>('workbench');const [mode,setMode]=useState<'upload'|'camera'>('upload');const [scenario,setScenario]=useState<Scenario>('W');const [health,setHealth]=useState<Health|null>(null);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [error,setError]=useState('');const [task,setTask]=useState<Task|null>(null);const [deleteId,setDeleteId]=useState<string|null>(null);const [list,setList]=useState<Task[]>([]);const [samples,setSamples]=useState<Sample[]>([]);const [busy,setBusy]=useState(false);const [stream,setStream]=useState<MediaStream|null>(null);const [recording,setRecording]=useState(false);const [countdown,setCountdown]=useState(0);const [recordSeconds,setRecordSeconds]=useState(0);const [guide,setGuide]=useState(false);const [modelInfo,setModelInfo]=useState(false);const input=useRef<HTMLInputElement>(null);const camera=useRef<HTMLVideoElement>(null);const recorder=useRef<MediaRecorder|null>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);const countdownTimer=useRef<ReturnType<typeof setInterval>|null>(null);const alive=useRef(true);const cameraAttempt=useRef(0);const pending=task?.status==='queued'||task?.status==='processing';
 const refresh=()=>api<Health>('/api/health').then(setHealth).catch(()=>setHealth(null));
 useEffect(()=>{alive.current=true;refresh();api<Sample[]>('/api/samples').then(setSamples).catch(()=>{});const saved=sessionStorage.getItem('gait-active-task');if(saved&&/^[0-9a-f]{32}$/.test(saved))api<Task>('/api/tasks/'+saved).then(t=>{if(alive.current){setTask(t);setScenario(t.scenario)}}).catch(()=>sessionStorage.removeItem('gait-active-task'));const timer=setInterval(refresh,15000);return()=>{alive.current=false;clearInterval(timer)}},[]);
 useEffect(()=>{if(task?.id)sessionStorage.setItem('gait-active-task',task.id);else sessionStorage.removeItem('gait-active-task')},[task?.id]);
 useEffect(()=>{if(!preview)return;return()=>URL.revokeObjectURL(preview)},[preview]);
 useEffect(()=>{if(camera.current&&stream){camera.current.srcObject=stream;camera.current.play().catch(()=>{})}return()=>{stream?.getTracks().forEach(t=>t.stop())}},[stream]);
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(countdownTimer.current)clearInterval(countdownTimer.current);if(recorder.current?.state==='recording')recorder.current.stop()},[]);
 useEffect(()=>{if(!pending||!task)return;let cancelled=false;const poll=setInterval(()=>api<Task>('/api/tasks/'+task.id).then(t=>{if(!cancelled){setTask(t);if(t.status==='completed'||t.status==='failed'){refresh();if(t.status==='failed')setError(t.error||'分析失败')}}}).catch(e=>{if(!cancelled)setError(e.message)}),800);return()=>{cancelled=true;clearInterval(poll)}},[task?.id,pending]);
 useEffect(()=>{if(page!=='workbench'||!task||!['completed','failed'].includes(task.status))return;const frame=requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelector(task.status==='completed'?'#report':'.capture-failure')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:task.status==='completed'?'start':'center'})));return()=>cancelAnimationFrame(frame)},[task?.id,task?.status,page]);
 useEffect(()=>{if(page==='history')api<Task[]>('/api/history').then(setList).catch(e=>setError(e.message));if(page!=='workbench'){stopCamera()}},[page]);
 function stopCamera(){cameraAttempt.current++;if(countdownTimer.current){clearInterval(countdownTimer.current);countdownTimer.current=null;setCountdown(0)}if(recorder.current?.state==='recording')recorder.current.stop();if(timer.current){clearInterval(timer.current);timer.current=null}setRecording(false);stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 function switchMode(next:'upload'|'camera'){if(next===mode||recording||countdown)return;stopCamera();setMode(next);setFile(null);setPreview('');setTask(null);setError('')}
 function selectFile(f:File){if(pending||busy||recording||countdown)return;setError('');setFile(null);setPreview('');setTask(null);if(f.size===0){setError('视频文件为空，请重新选择');return}if(f.size>200*1024*1024){setError('视频超过 200 MB，请截取后重试');return}if(!/\.(mp4|mov|avi|webm)$/i.test(f.name)){setError('支持 MP4、MOV、AVI、WebM 文件');return}stopCamera();setFile(f);setPreview(URL.createObjectURL(f))}
 async function enableCamera(){if(pending||busy)return;const attempt=++cameraAttempt.current;setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('当前浏览器无法访问摄像头，请使用本地地址或上传视频');const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:false});if(!alive.current||attempt!==cameraAttempt.current){s.getTracks().forEach(t=>t.stop());return}setFile(null);setPreview('');setTask(null);setStream(s)}catch(e){if(!alive.current||attempt!==cameraAttempt.current)return;const err=e as Error;setError(err.name==='NotAllowedError'?'摄像头权限被拒绝，请在浏览器地址栏允许摄像头，或上传视频':err.name==='NotFoundError'?'未找到摄像头，请连接设备或上传视频':err.message)}}
 function beginRecord(){if(!stream||countdown||recording)return;setCountdown(3);let left=3;countdownTimer.current=setInterval(()=>{left--;setCountdown(left);if(left===0){clearInterval(countdownTimer.current!);countdownTimer.current=null;try{if(typeof MediaRecorder==='undefined')throw new Error('浏览器不支持录制，请上传视频');const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw new Error('浏览器没有可用视频录制编码');const rec=new MediaRecorder(stream,{mimeType:mime});const attempt=cameraAttempt.current;recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=()=>{setError('录制失败，请重试');if(rec.state==='recording')rec.stop()};rec.onstop=()=>{if(timer.current)clearInterval(timer.current);setRecording(false);if(attempt!==cameraAttempt.current)return;const blob=new Blob(chunks,{type:mime});if(blob.size>200*1024*1024){setError('录制视频超过 200 MB，请缩短时长重录');stream.getTracks().forEach(t=>t.stop());setStream(null);return}if(!blob.size){setError('录制文件为空，请重新录制');stream.getTracks().forEach(t=>t.stop());setStream(null);return}if(blob.size){const f=new File([blob],`现场行走-${Date.now()}.${mime.includes('mp4')?'mp4':'webm'}`,{type:mime});setFile(f);setPreview(URL.createObjectURL(f))}stream.getTracks().forEach(t=>t.stop());setStream(null)};rec.start(500);setRecording(true);setRecordSeconds(0);let secs=0;timer.current=setInterval(()=>{secs++;setRecordSeconds(secs);if(secs>=120&&rec.state==='recording')rec.stop()},1000)}catch(e){setError((e as Error).message)}}},1000)}
 async function start(sample?:Sample){setError('');setBusy(true);try{let out:{id:string};if(sample){out=await api('/api/samples/'+sample.id+'/analyze',{method:'POST'});setScenario(sample.scenario);setPage('workbench');stopCamera();setFile(null);setPreview('')}else{if(!file)throw new Error('请选择或录制视频');const data=new FormData();data.append('file',file);data.append('scenario',scenario);out=await api('/api/tasks',{method:'POST',body:data})}setTask(await api<Task>('/api/tasks/'+out.id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(id:string){try{await api('/api/tasks/'+id,{method:'DELETE'});setList(v=>v.filter(t=>t.id!==id));if(task?.id===id)setTask(null);setDeleteId(null)}catch(e){setError((e as Error).message)}}
 async function open(id:string){try{const t=await api<Task>('/api/tasks/'+id);setTask(t);setScenario(t.scenario);setPage('workbench');setError(t.error||'')}catch(e){setError((e as Error).message)}}
 const readyResult=task?.status==='completed'&&task.result;
 const progressSteps=task?.mode==='sample'?['读取数据','运行模型','生成结果']:['读取视频','二维姿态','候选周期','三维估计','模型推理','生成结果'];
 const progressIndex=task?.mode==='sample'?(task.stage.includes('结果')?2:task.stage.includes('模型')?1:0):task?.stage.includes('结果')?5:task?.stage.includes('模型')?4:task?.stage.includes('三维')?3:task?.stage.includes('周期')?2:/二维|主体|骨架|姿态/.test(task?.stage||'')?1:0;
 return <div className="app"><aside className="sidebar no-print"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('workbench')}}><Activity size={34} strokeWidth={2.5}/><div>步态研究<span>G A I T L A B</span></div></a><nav>{[{id:'workbench' as const,name:'评估工作台',icon:LayoutDashboard},{id:'history' as const,name:'评估记录',icon:History},{id:'samples' as const,name:'演示样例',icon:Play}].map(item=><button key={item.id} className={page===item.id?'active':''} onClick={()=>{setPage(item.id);setError('')}}><item.icon size={20}/>{item.name}{page===item.id&&<ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-footer"><Monitor size={18}/><div>本地运行</div></div></aside>
 <div className="main"><nav className="mobile-nav no-print"><button onClick={()=>setPage('workbench')}>评估工作台</button><button onClick={()=>setPage('history')}>评估记录</button><button onClick={()=>setPage('samples')}>演示样例</button></nav><div className="service-bar no-print"><button onClick={()=>setModelInfo(true)}><span className={'status-dot '+(health?'online':'')}/><Link2 size={14}/>{health?'本地服务已连接':'本地服务未连接'}</button></div><main><header className="page-heading no-print"><div><h1>{page==='workbench'?'步态评估工作台':page==='history'?'评估记录':'演示样例'}</h1></div><button className="text-button" onClick={()=>setGuide(true)}><BookOpen size={19}/>采集指南</button></header>
 {error&&task?.status!=='failed'&&<div className="notice error no-print" role="alert"><AlertCircle size={19}/><span>{error}</span><button aria-label="关闭错误提示" onClick={()=>setError('')}><X size={17}/></button></div>}
 {page==='workbench'&&<><div className="workflow-bar no-print">{[{n:'01',title:'采集视频',icon:Video},{n:'02',title:'姿态分析',icon:ScanLine},{n:'03',title:'查看结果',icon:Activity}].map((step,i)=><div className={'workflow-step '+((readyResult?i===2:pending?i===1:i===0)?'current':'')} key={step.n}><span className="workflow-number">{step.n}</span><step.icon size={19}/><b>{step.title}</b>{i<2&&<ArrowRight size={16} className="workflow-arrow"/>}</div>)}</div><div className="scenario-row no-print"><div className="scenario-options">{(['W','OW','WT'] as Scenario[]).map(s=><button disabled={!!pending||busy||recording||!!countdown} className={scenario===s?'selected':''} key={s} onClick={()=>{if(s===scenario)return;stopCamera();setScenario(s);setTask(null);setFile(null);setPreview('');setError('')}}><b>{s}</b>{scenarios[s].name}</button>)}</div></div>
 {!readyResult&&!pending&&<div className="capture-layout no-print"><section className="capture-panel"><div className="tabs"><button disabled={busy||recording||!!countdown} className={mode==='upload'?'selected':''} onClick={()=>switchMode('upload')}><UploadCloud size={17}/>上传视频</button><button disabled={busy} className={mode==='camera'?'selected':''} onClick={()=>switchMode('camera')}><Camera size={17}/>摄像头录制</button></div><input ref={input} type="file" accept=".mp4,.mov,.avi,.webm" hidden onChange={e=>{if(e.target.files?.[0])selectFile(e.target.files[0]);e.target.value=''}}/>
 <div className={'capture-canvas '+(preview||stream?'has-media':'')+(file?.name.toLowerCase().endsWith('.avi')?' avi-preview':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!pending&&!recording&&e.dataTransfer.files[0])selectFile(e.dataTransfer.files[0])}}>{stream?<><video ref={camera} muted autoPlay playsInline/><div className="frame-guide"/><div className="camera-tip">请保持全身与双脚完整入镜</div>{countdown>0&&<div className="countdown">{countdown}</div>}{recording&&<div className="record-label"><i/>{recordSeconds}s / 120s</div>}</>:preview&&file?.name.toLowerCase().endsWith('.avi')?<div className="avi-file-ready"><span><FileVideo2 size={43}/></span><h2>视频已就绪</h2><p>{file.name}</p><small>AVI 原片无法在浏览器内预览；分析服务会直接读取视频帧</small></div>:preview?<video key={preview} src={preview} controls onLoadedMetadata={e=>{if(e.currentTarget.duration>120.1){setError('视频超过两分钟，请截取后重试');setFile(null);setPreview('')}}}/>:<><div className="upload-icon">{mode==='upload'?<UploadCloud size={55} strokeWidth={1.35}/>:<Camera size={50} strokeWidth={1.35}/>}</div><h2>{mode==='upload'?'上传一段行走视频':'录制一段完整行走'}</h2><p>{mode==='upload'?'也可拖放到这里':'确认全身入镜后录制'}</p><small>MP4 · MOV · AVI · WebM　≤2 分钟　≤200 MB</small><button className="secondary" onClick={()=>mode==='upload'?input.current?.click():enableCamera()}>{mode==='upload'?<FolderOpen size={17}/>:<Camera size={17}/>} {mode==='upload'?'选择视频':'打开摄像头'}</button></>}</div>
 <div className="capture-actions">{stream?<button className={recording?'stop-button':'secondary'} disabled={countdown>0} onClick={()=>recording?recorder.current?.stop():beginRecord()}>{recording?<Square size={16}/>:<Video size={17}/>} {recording?'停止并预览':countdown?'准备录制…':'开始录制'}</button>:preview?<><span title={file?.name}>{file?.name}</span><button className="text-button" disabled={!!pending||busy} onClick={()=>{setFile(null);setPreview('');setTask(null)}}><RefreshCw size={15}/>重新采集</button></>:null}</div><button className={'primary start-analysis'+(file?' ready':'')} disabled={!file||!!pending||busy||recording||!!countdown} onClick={()=>start()}>{pending||busy?<LoaderCircle size={18} className="spin"/>:<Play size={17}/>} {pending?'正在分析':busy?'正在上传':health?.video.ready||scenario==='W'&&health?.video.demo_w_grading?'开始分析':'提取视频姿态'}<ArrowRight size={18}/></button>{task?.status==='failed'&&<div className="capture-failure" role="alert"><AlertCircle size={19}/><div><b>分析未完成</b><p>{task.error||error||'请重新采集后重试'}</p><button className="text-button" onClick={()=>input.current?.click()}>重新选择视频</button></div></div>}{health&&!health.video.ready&&<p className="pipeline-note"><AlertCircle size={14}/><span>{health.video.demo_w_grading&&scenario==='W'?'实验性分级 · 未验证':'当前视频仅输出姿态预览'}</span><button onClick={()=>setModelInfo(true)}>了解限制</button></p>}</section>
 <aside className="guide-panel"><h2><BookOpen size={21}/>录制前准备</h2>{[{title:'全身入镜',text:'头脚完整可见'},{title:'保持单人行走',text:'画面仅一人'},{title:'光线充足',text:'避免逆光和遮挡'},{title:'完整步态周期',text:scenario==='W'?'连续走过数步':scenario==='OW'?'完成跨障碍行走':'完成边走边说'}].map((g,i)=><div className="guide-step" key={g.title}><span>{i+1}</span><div><h3>{g.title}</h3><p>{g.text}</p></div></div>)}<div className="camera-diagram"><div className="camera-device"><Camera size={27}/><div/></div><div className="field-of-view"/><div className="person-diagram"><span/><i/><b/><em/></div><div className="height-guide">全身<br/>入镜</div><div className="floor-line"/><p>固定机位 · 留出完整行走空间</p></div></aside></div>}
 {pending&&task&&<section className={'progress-panel no-print'+(task.mode==='sample'?' sample-progress':'')}><div className="progress-main"><span className="progress-orb"><LoaderCircle className="spin" size={29}/></span><div><small>{task.name}</small><h2>{task.mode==='sample'?'正在运行样例模型':'正在分析步态视频'}</h2><p>{task.stage}</p></div><span className="progress-elapsed"><Clock size={15}/>{task.elapsed.toFixed(1)} 秒</span></div><ol>{progressSteps.map((s,i)=><li className={i===progressIndex?'current':i<progressIndex?'done':''} key={s}><span>{i<progressIndex?<Check size={13}/>:i+1}</span>{s}</li>)}</ol></section>}
 {readyResult?<><div className="result-toolbar no-print"><button className="text-button" onClick={()=>{setTask(null);setFile(null);setPreview('');setError('')}}><RefreshCw size={16}/>开始新的评估</button></div><ResultView task={task!}/></>:pending?null:<section className="empty-results no-print"><div className="section-heading"><h2><Activity size={21}/>分析结果</h2></div><div className="empty-chart"><div className="empty-axis"><span>角度（°）</span><span>180</span><span>90</span><span>0</span></div><div className="empty-chart-main"><Activity size={30}/><p>等待分析结果</p></div></div></section>}</>}
 {page==='samples'&&<section className="samples-page no-print"><div className="notice"><FileText size={19}/><span>已有数据样例 · 非现场视频 · 不代表新视频识别准确率</span></div><div className="sample-list">{samples.map(s=><article key={s.id}><div className="sample-thumb"><Activity size={33}/><span>{s.scenario}</span></div><div className="sample-text"><h3>{s.name}</h3><p>{scenarios[s.scenario].name} · {s.stride_count} 个周期 · 参考标注 {s.reference_label}</p><small>{s.description}</small></div><button className="secondary" disabled={busy||!!pending} onClick={()=>start(s)}><Play size={16}/>运行模型</button></article>)}</div>{samples.length===0&&<div className="empty-state">样例清单尚未生成，请先完成模型核验。</div>}</section>}
 {page==='history'&&<section className="history-panel no-print"><div className="section-heading"><h2>本地评估记录</h2><button className="text-button" onClick={()=>api<Task[]>('/api/history').then(setList).catch(e=>setError(e.message))}><RefreshCw size={15}/>刷新</button></div>{list.length?<div className="table-wrap"><table><thead><tr><th>评估内容</th><th>场景</th><th>来源</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody>{list.map(t=><tr key={t.id}><td title={t.name}>{t.name}</td><td>{t.scenario}</td><td>{t.mode==='sample'?'已有数据样例':'上传 / 录制'}</td><td><span className={'record-status '+t.status}>{t.status==='completed'?'已完成':t.status==='failed'?'失败': '分析中'}</span></td><td>{new Date(t.created).toLocaleString('zh-CN')}</td><td><button className="text-button" onClick={()=>open(t.id)}>查看</button><button className="icon-button" disabled={['processing','queued'].includes(t.status)} onClick={()=>setDeleteId(t.id)} aria-label={'删除 '+t.name}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>:<div className="empty-state"><History size={32}/><h3>还没有评估记录</h3><p>完成一次分析后，结果会自动保存在这里。</p><button className="secondary" onClick={()=>setPage('workbench')}>开始评估</button></div>}</section>}
 </main></div>
 {(guide||modelInfo)&&<div className="modal-backdrop no-print" onClick={()=>{setGuide(false);setModelInfo(false)}}><section className="modal" role="dialog" aria-modal="true" aria-label={guide?'采集指南':'模型接入状态'} onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭" onClick={()=>{setGuide(false);setModelInfo(false)}}><X/></button><h2>{guide?'采集与演示指南':'模型接入状态'}</h2>{guide?<><p>1. 选择真实采集场景：W 普通行走、OW 跨障碍行走、WT 边走边说。</p><p>2. 使用固定机位，确保受试者全身和双脚入镜；录制多个完整周期。</p><p>3. 停止录制并回放确认，随后提交分析。录制不采集音频。</p><p>4. 等待真实处理阶段结束，查看结果并导出报告。</p><p>5. 答辩备用演示请使用“演示样例”，其来源会明确显示在结果中。</p></>:<><p>{health?'服务已连接，运行在本机。':'服务未连接，请先启动本地服务。'}</p>{health&&Object.entries(health.routes).map(([s,r])=><div className="model-route" key={s}><strong>{s} · {r.name}</strong><p>{r.input}</p><small>{r.selection}</small></div>)}<p>{health?.video.ready?'视频预处理已核验':health?.video.reason}</p>{health?.video.missing?.length? <details><summary>待核验组件</summary><ul>{health.video.missing.map(m=><li key={m}>{m}</li>)}</ul></details>:null}</>}</section></div>}
 {deleteId&&<div className="modal-backdrop no-print" onClick={()=>setDeleteId(null)}><section className="modal delete-dialog" role="dialog" aria-modal="true" aria-label="删除评估记录" onClick={e=>e.stopPropagation()}><span className="delete-icon"><Trash2 size={23}/></span><h2>删除这条评估记录？</h2><p>本地视频和分析产物会一起删除，删除后无法恢复。</p><div className="delete-actions"><button className="secondary" onClick={()=>setDeleteId(null)}>取消</button><button className="danger-button" onClick={()=>remove(deleteId)}>删除记录</button></div></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
